### ISSUE TITLE
Chapter 9 canvas examples don't match current prescript-canvas api

### ISSUE THREAD

**Issue by kofno** [paf31/purescript-book#10]
For example, this line (https://github.com/paf31/purescript-book/blob/master/chapter9/src/Rectangle.purs#L8) doesn't work anymore, because getCanvasElementById uses Maybe.

getCanvasElementById :: forall eff. String -> Eff (canvas :: Canvas | eff) (Maybe CanvasElement)

**Comment by paf31** [comment]
But it still builds, right? The bower.json file references versions `~0.1.4`.

**Comment by kofno** [comment]
You’re totally correct. I withdraw the issue :)
