### ISSUE TITLE
Corrections for Chapter 8

### ISSUE THREAD

**Issue by gabejohnson** [paf31/purescript-book#101]
Some minor things I noticed while working through Chapter 8:

There is an extra `=` at
https://github.com/paf31/purescript-book/blob/b1790a9b7e977c2104b83f410f32d829e751d21b/text/chapter8.md#L864-L865

There are references to an `Object` constructor at https://github.com/paf31/purescript-book/blob/b1790a9b7e977c2104b83f410f32d829e751d21b/text/chapter8.md#L552 and https://github.com/paf31/purescript-book/blob/b1790a9b7e977c2104b83f410f32d829e751d21b/text/chapter8.md#L578
Should this be `Record`?

There should be a space separating "Home" and "Phone", etc. at https://github.com/paf31/purescript-book/blob/b1790a9b7e977c2104b83f410f32d829e751d21b/exercises/chapter8/src/Data/AddressBook.purs#L58-L61

**Comment by paf31** [comment]
Thanks very much for the detailed write up!
