### ISSUE TITLE
Missing word?

### ISSUE THREAD

**Issue by craigdallimore** [paf31/purescript-book#104]
[Location](https://github.com/paf31/purescript-book/blame/master/text/chapter11.md#L465)

>  The `Exception` effect only supports exceptions of one type, namely JavaScript's `Error` type, whereas `ExceptT` supports errors of type.

I suspect something is missing, should it say something like

> ... whereas `ExceptT` supports errors of various types.

?

**Comment by paf31** [comment]
Fixed, thanks!
