### ISSUE TITLE
Chapter 9 doesn't build on purs 0.11.6

### ISSUE THREAD

**Issue by tyehle** [paf31/purescript-book#107]
Seems that ignoring return values in do notation was made illegal at some point. I get many errors like this:

```
A result of type
               
  Context2D
               
was implicitly discarded in a do notation block.
You can use _ <- ... to explicitly discard the result.
```

adding `void $ ...` to these lines fixes the issue.

**Comment by paf31** [comment]
Fixed, thanks!
