### ISSUE TITLE
Unable to build Chapter3 code

### ISSUE THREAD

**Issue by ThomasCrvsr** [paf31/purescript-book#11]
Hello,

I was working on the Chapter 3, but the compilation doesn't work related to an error in the purescript-foldable-trasversal module :
``` 
Warning: Error at bower_components/purescript-foldable-traversable/src/Data/Foldable.purs line 6, column 1 - line 7, column 1: 
Error in module Data.Foldable
Cannot import unknown module 'Data.Eq' Use --force to continue.
```
I guess it's related to this issue : https://github.com/purescript/purescript/issues/769

Do you have any solution to fix that ?

**Comment by paf31** [comment]
Can you `git pull && bower update` and try again please?

**Comment by ThomasCrvsr** [comment]
Awesome, it works perfectly, thanks a lot !
