### ISSUE TITLE
Ch4: fib 0 = 0

### ISSUE THREAD

**Issue by MarianJancar** [paf31/purescript-book#127]

**Comment by paf31** [comment]
Can you please explain?

**Comment by MarianJancar** [comment]
There is 'fib 0 = 1' in the book.

**Comment by CYBAI** [comment]
Reference from wikipedia of [Fibonacci number](https://en.wikipedia.org/wiki/Fibonacci_number).

> By definition, the first two numbers in the Fibonacci sequence are either 1 and 1, or 0 and 1, depending on the chosen starting point of the sequence, and each subsequent number is the sum of the previous two.

I think it's okay to start with `1` and `1`.

**Comment by MarianJancar** [comment]
Ok.
Nevertheless, the sequence starting with 1 feels Pascal-like indexed, ie fib 1 = 1, fib 2 = 1.
When defined like fib 0 = 1, fib 1 = 1, and extended to negative numbers, it is 'symmetric' around -1, instead of around 0.
