### ISSUE TITLE
Errors while building Chapter 10

### ISSUE THREAD

**Issue by ThomasCrvsr** [paf31/purescript-book#14]
While building the code in Chapter 10 using grunt, I have errors regarding Data.Monoid.Additive module : "Unknown type Semiring" (line 48 and 51)

**Comment by SimonRichardson** [comment]
You've got two options:

- Put older versions of the libraries in your bower/package file. You might have to spend sometime trying to work out which version of which library plays nicely with each other though!
- Update to the latest purescript, which includes Semiring in the prelude. You may have to remove `.psci_modules` in your folder to you get the latest code as well.

**Comment by ThomasCrvsr** [comment]
Thanks for the reply. I should have closed this issue ^^ I updated my version of Purescript, it was the easiest solution I found :)
