### ISSUE TITLE
Chapter 4.9: Duplicate code examples

### ISSUE THREAD

**Issue by Warry** [paf31/purescript-book#16]
![screen shot 2015-03-25 at 18 48 41](https://cloud.githubusercontent.com/assets/197573/6831272/9545e4bc-d31f-11e4-98e7-db8132c4293d.png)

Both examples are the same, for different results.

**Comment by paf31** [comment]
They're different in one character :) Compare `i..n` and `1..n`.

**Comment by Warry** [comment]
ow... sorry...
