### ISSUE TITLE
Chapter 8 doesn't compile

### ISSUE THREAD

**Issue by beckyconning** [paf31/purescript-book#18]
It doesn't compile unless the exercises from chapter 7 were completed in a very specific manner leaving the `Person` type unchanged, an unchanged `validatePerson` function renamed to `validatePerson'` and `examplePerson` unchanged.

Even once these errors have been fixed it does not compile.

```
Running "psc:all" (psc) task
>> Error creating file dist/Main.js
>> 
Warning: Error in module Data.AddressBook.UI:
Error in value declaration validateControls:
Error checking that type
  Control.Monad.Eff.Eff (trace :: Debug.Trace.Trace | u9785) u9782
subsumes type
  Control.Monad.Eff.Eff (dom :: Control.Monad.Eff.DOM.DOM, trace :: Debug.Trace.Trace | eff9780) (Data.Either.Either [Prim.String] Data.AddressBook.Person)
Error at src/Data/AddressBook/UI.purs line 50, column 1 - line 64, column 1:
  Cannot unify type
    Data.Validation.V
  with type
    Data.Either.Either
See https://github.com/purescript/purescript/wiki/Error-Code-ErrorUnifyingTypes for more information, or to contribute content related to this error. Use --force to continue.
```

I imagine this is because there is some `validatePerson'` which hasn't been committed.

**Comment by beckyconning** [comment]
See https://github.com/paf31/purescript-book/pull/19

**Comment by paf31** [comment]
Fixed in the new version of the book, the code is no longer shared between chapters.
