### ISSUE TITLE
Chapter 11 runtime error

### ISSUE THREAD

**Issue by codygman** [paf31/purescript-book#21]
It seems that chapter 11 depends on having already done:

```shell
npm install yargs
```

But there isn't anything in the book and I'm not quite sure why it's necessary. I know at least one other user had this problem as well:

http://ircbrowse.net/browse/purescript?id=4302&timestamp=1414361749#t1414361749

**Comment by paf31** [comment]
This is fixed in the new version of the book, thanks.
