### ISSUE TITLE
`pulp build --to dist/Main.js` failed but `pulp build --to Main.js` succeeded

### ISSUE THREAD

**Issue by TorosFanny** [paf31/purescript-book#26]
### In Chapter8:
The following command is roughly the same as https://leanpub.com/purescript/read#leanpub-auto-the-eff-monad-1, but failed like this:
```
qs@BF:~/../chapter8$ pulp build -O --to dist/Main.js
* Building project in /home/qs/Data/Documents/SourceCode/PureScript/purescript-book/chapter8
* Build successful.
* Bundling Javascript...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open 'dist/Main.js'
    at Error (native)
```
However the following succeeded without any problem.
```
qs@BF:~/../chapter8$ pulp build -O --to Main.js
* Building project in /home/qs/Data/Documents/SourceCode/PureScript/purescript-book/chapter8
* Build successful.
* Bundling Javascript...
* Bundled.
```
And if I modify the `html/index.html` to point to `Main.js`, the web page functions as expected.

### My platform:
 1. Operating System: Ubuntu 14.04.3
 2. PureScript: pre-compiled binary 0.7.2.0

**Comment by TorosFanny** [comment]
Make sure directory `dist` exist in advance of `pulp build -O --to dist/Main.js`.

**Comment by paf31** [comment]
Thanks, I'll add a note to the book about this :+1:
