### ISSUE TITLE
Missing Gruntfile referenced in Chapter 8

### ISSUE THREAD

**Issue by cdparks** [paf31/purescript-book#29]
Section 8.2 says "The source code for this project builds on the source for the previous chapter, and as such, uses the Grunt build script to include its source files."

Later the book instructs the reader to "... build with Grunt, and open the html/index.html file in your web browser."

I don't see any Gruntfile in the repo. Is this text outdated or is the reader meant to write their own Gruntfile?

**Comment by paf31** [comment]
Sorry, I'll update this.

**Comment by paf31** [comment]
By the way, the solution is to use `pulp build --to dist/Main.js`.

**Comment by cdparks** [comment]
Ah, that makes sense. Thanks for the quick reply!
