### ISSUE TITLE
purescript 0.7 Number /= Int bugs in text

### ISSUE THREAD

**Issue by joelgrus** [paf31/purescript-book#30]
In section 5.5, the `gcd` function doesn't work, the type is `Number -> Number -> Number`, but the definition uses an Int literal. 

similarly, the `showPicture` example in 5.15 uses `Int` literals, I guess it should be

`showPicture [Line (Point { x: 0.0, y: 0.0 }) (Point { x: 1.0, y: 1.0 })]`

I wouldn't be surprised if there's more of these, those are the two I've found.

**Comment by paf31** [comment]
Thanks, I'll fix these.
