### ISSUE TITLE
Chapter 4.16 needs to explain how to install purescript-path

### ISSUE THREAD

**Issue by endeavour** [paf31/purescript-book#32]
It isn't very clear in the book that an additional dependency is needed. Also it seems that pulp currently fails to install this module due to some conflicting dependencies.

**Comment by paf31** [comment]
`purescript-path` isn't used in the book.

**Comment by paf31** [comment]
I think you need the `Path` module defined in the book repo.

**Comment by endeavour** [comment]
Ah silly me! Might be worth making this clearer in the book though?
