### ISSUE TITLE
Some questions about current version

### ISSUE THREAD

**Issue by izgzhen** [paf31/purescript-book#33]
Some of the possible buggy things I observed. Just for your reference.

1. In the "Conclusion" section of "Generative Test" Chapter, the first one mentioned Grunt like that "We saw how to automate QuickCheck tests using Grunt." But I can find anywhere mentioning Grunt more in this chapter.
2. In the 12.7 section, `par` function is used but current `purescript-parallel` package don't have such interface anymore as I found. It might be misleading.
3. Just at the beginning of 11.11 section, there is one line of type class definition `class (Applicative f, Plus f) <= Alternative f where`, which ends up with a strange `where`
4. 11.9 section mentioned ` Control.Monad.Identity` module, but it doesn't exist now. It should be `Data.Identity` I think.

I hope these can help you. BYW, this is an excellent book!

**Comment by paf31** [comment]
:+1: Thanks for all the pointers, I'll release an updated version now.
