### ISSUE TITLE
Chapter 7 - f used to represent both function and functor in the same paragraph, sort of confusing

### ISSUE THREAD

**Issue by joelgrus** [paf31/purescript-book#34]
section 7.4

For functions of two arguments, we have a curried function f with type a -> b -> c, say. This is equivalent to the type a -> (b -> c), so we can apply map to f to get a new function of type f a -> f (b -> c). Partially applying this function to the first lifted argument (of type f a), we get a new wrapped function of type f (b -> c). We can then use apply to apply the second lifted argument (of type f b) to get our final value of type f c.

Putting this all together, we see that if we have values x :: f a and y :: f b, then the expression (f <$> x) <_> y has type f c (remember, this expression is equivalent to apply (map f x) y). The precedence rules defined in the Prelude allow us to remove the parentheses: f <$> x <_> y.

**Comment by paf31** [comment]
Ah good point. Will fix, thanks.

**Comment by paf31** [comment]
This is fixed on the 0.10 branch, thanks!
