### ISSUE TITLE
Fix for section 4.15, exercise 3

### ISSUE THREAD

**Issue by pyykkis** [paf31/purescript-book#35]
Hi,

I had some troubles getting over the exercise until someone at the #purescript/freenode guided me to Data.Array.Unsafe. Could it be added it the exercise? I also noticed a small typo (head x) vs. (head xs), also fixed below. 

```purescipt
module Ex4 where

import Prelude
import Data.Array.Unsafe -- Add import clause

count :: forall a. (a -> Boolean) -> Array a -> Int
count _ [] = 0
count p xs = if p (head xs) -- Fix typo: (head x) ==> (head xs)
    then count p (tail xs) + 1
    else count p (tail xs)
```

Thanks for making browser development bearable again! :)

**Comment by paf31** [comment]
Fixed, thanks!
