### ISSUE TITLE
Many (all?) of the examples won't build.

### ISSUE THREAD

**Issue by enolan** [paf31/purescript-book#36]
In, for example, chapter 3, the text of the book tells me to run `pulp dep update` and then `pulp build`. Running `pulp dep update` gives me a warning that it's deprecated and to use Bower instead. After the warning, it installs some things and then says:
```
Unable to find a suitable version for purescript-foldable-traversable, please choose one:
    1) purescript-foldable-traversable#~0.2.1 which resolved to 0.2.1 and is required by purescript-identity#0.2.0, purescript-lazy#0.2.0, purescript-lists#0.5.0
    2) purescript-foldable-traversable#^0.4.0 which resolved to 0.4.2 and is required by purescript-tuples#0.4.0

Prefix the choice with ! to persist it to bower.json

? Answer 
```
In the README, there are different instructions. I'm supposed to run `npm install`, `bower update`, and `grunt`. Bower gives me the same messages about dependency conflicts. In addition, running `grunt` gives this message:
```
$ grunt
Running "psc:all" (psc) task
>> Error creating file dist/Main.js
>> 
Warning: Invalid option `--module=Data.PhoneBook'

Usage: psc [FILE] [-f|--ffi ARG] [-o|--output ARG] [--no-tco] [--no-magic-do]
           [--no-opts] [-v|--verbose-errors] [-c|--comments]
           [-r|--require-path ARG] [--source-maps] [-p|--no-prefix]
           [--json-errors] Use --force to continue.

Aborted due to warnings.
```

There are more problems with the other examples.

On the plus side, the actual text of the book is very good.

Versions:
```
$ npm -v
2.14.12

$ grunt --version
grunt-cli v0.1.13
grunt v0.4.5

$ bower --version
1.7.7

$ pulp --version
Pulp version 8.0.0
psc version 0.8.2.0 using /usr/bin/psc

$ psc --version
0.8.2.0

$ node --version
v4.3.2
```

**Comment by AppShipIt** [comment]
I'm thinking of ways to automate testing examples for mine. I'll report back what I find.

**Comment by paf31** [comment]
The books needs updating, it's on my todo list.

**Comment by rmies** [comment]
Not to be presumptuous, but any idea when this might happen?

**Comment by paf31** [comment]
I need to make a full pass through the book again after 0.8, so it's on my list, but it'll probably be a month or so before I find time.

**Comment by rmies** [comment]
Great, thank you!

**Comment by paf31** [comment]
What README are you referring to? What `Gruntfile` are you using?

**Comment by enolan** [comment]
Well, now I feel dumb. My checkout was really out of date. The READMEs aren't there anymore, neither is Grunt, and the dependencies are updated.
