### ISSUE TITLE
Missing Data.List.Cons in 0.8.3

### ISSUE THREAD

**Issue by arnau** [paf31/purescript-book#37]
Hi, I'm following this book using Purescript 0.8.3.0 installed via `npm` (Debian).

Chapter 3 defines the following function https://github.com/paf31/purescript-book/blob/master/chapter3/src/Data/AddressBook.purs#L34

```purescript
insertEntry entry book = Cons entry book
```

but fails with `Unknown data constructor Cons`. Checking purescript's changelog https://github.com/purescript/purescript/releases/tag/v0.8.2 it suggests to me that the new way of expressing this should be

```purescript
insertEntry entry book = entry : book
```

or 

```purescript
insertEntry = (:)
```

Is this correct or I am missing something with `Cons`?

**Comment by arnau** [comment]
Ok, got it, it's a matter of importing it like

```purescript
import Data.List (List(Cons))
```

**Comment by paf31** [comment]
Yes, that's right, or `import Data.List (List(..))`.
