### ISSUE TITLE
New dependencies not documented (control + lists)

### ISSUE THREAD

**Issue by dmcgrady** [paf31/purescript-book#42]
While working my way through the book, using the latest 9.1 version of Purescript, I noticed I had to install two additional dependencies that weren't documented in the book for Chapter 3 . Not sure if this is the right place to suggest fixes to the book or not but here they are:

```
 bower install purescript-control
 bower install purescript-lists
```

In order for these two imports to work:

```
import Control.Plus (empty)
import Data.List (List(..), filter, head)
```

I believe they were separated into their own libraries recently.

Thanks for writing the book, it's been very helpful.

**Comment by paf31** [comment]
The "Project Setup" section recommends using `bower update` in the `chapter3` directory, which should pull these dependencies in.
