### ISSUE TITLE
Chapter 6 - repeatAction instance broken: Exercise 1 - Chapter 6.10 - Superclasses 

### ISSUE THREAD

**Issue by abuibrahim** [paf31/purescript-book#43]
Since `Int` is not a `Monoid` for the repeatAction instance to work the class should be:

``` purescript
class Monoid m <= Action a m where
  act :: a -> m -> m
```

**Comment by i-am-tom** [comment]
:+1: - came here to say exactly the same thing :)

**Comment by paf31** [comment]
This will be fixed in the next release, thanks!
