### ISSUE TITLE
Chapter 5 - Data.Array.Unsafe dependency in 5.10

### ISSUE THREAD

**Issue by dlants** [paf31/purescript-book#45]
In chapter 4.14 the exercise asks to rewrite:

```
 import Prelude
 import Data.Array.Unsafe (head, tail)

 count :: forall a. (a -> Boolean) -> Array a -> Int
 count _ [] = 0
 count p xs = if p (unsafePartial head xs)
                then count p (unsafePartial tail xs) + 1
                else count p (unsafePartial tail xs)
```

using a fold. However, I can't figure out what the corresponding bower import for Data.Array.Unsafe should be.

**Comment by paf31** [comment]
I think this should be `Data.Array.Partial`.

**Comment by brynedwards** [comment]
Hi, just FYI it also mentions ```Data.Array.Unsafe``` in an example in [5.10](https://leanpub.com/purescript/read#leanpub-auto-case-expressions), which is also missing ```unsafePartial```. I'm assuming it should be:
```
import Data.Array.Partial (tail)
import Data.Foldable (sum)
import Partial.Unsafe (unsafePartial)

lzs :: Array Int -> Array Int
lzs [] = []
lzs xs = case sum xs of
0 -> xs
_ -> lzs (unsafePartial tail xs)
```

**Comment by paf31** [comment]
Fixed, thanks!
