### ISSUE TITLE
Chapter 9 - Random example

### ISSUE THREAD

**Issue by doppioslash** [paf31/purescript-book#46]
I'm getting

```
at canvas/src/Example/Random.purs line 16, column 1 - line 37, column 20

  The last statement in a 'do' block must be an expression, but this block ends with a let binding.
```

from the Example.Random code at 9.5.

**Comment by paf31** [comment]
This works for me, but I think it can be worded better so that it's clearer where the code sample ends. I'll improve it in the next release of the book, thanks!
