### ISSUE TITLE
Updates for `0.10.2` are available

### ISSUE THREAD

**Issue by sectore** [paf31/purescript-book#51]
At the [fork / branch "update-0.10.2"](https://github.com/sectore/purescript-book/tree/update-0.10.2) you will find updates of all chapters to latest [`0.10.2`](https://github.com/purescript/purescript/releases/tag/v0.10.2). 

Commits overview: https://github.com/sectore/purescript-book/commits/update-0.10.2 

P.S. `purescript-book` [does not accept any pull request](https://github.com/paf31/purescript-book/blob/master/CONTRIBUTING.md) , right?

-Jens

**Comment by paf31** [comment]
Thanks for this. I appreciate the work, but I'm going through and updating the code and book text now, to make sure everything is in sync with the text. I'll leave this open for any readers looking for working code for 0.10.2 until those changes get merged though.
