### ISSUE TITLE
Chapter 3 - Diagonal example missing logShow import

### ISSUE THREAD

**Issue by kristianmandrup** [paf31/purescript-book#52]
The diagonal example should be:

```purs
module Main where
import Math (sqrt)
import Control.Monad.Eff.Console (logShow)
import Prelude
diagonal w h = sqrt (w * w + h * h)
main = logShow (diagonal 3.0 4.0)
```

I found first import of `logShow` in Chapter 7

**Comment by naomik** [comment]
Ran into the same problem. Changing my import from `log` to `logShow` also fixed the problem.

**Comment by paf31** [comment]
The code in the book uses an open import, so this shouldn't be an issue any more.
