### ISSUE TITLE
forall never really explained

### ISSUE THREAD

**Issue by kristianmandrup** [paf31/purescript-book#55]
```
> :type flip
forall a b c. (a -> b -> c) -> b -> a -> c
```

The keyword `forall` here indicates that flip has a universally quantified type. It means that we can substitute any types for a, b and c, and flip will work with those types.

Also what does `c.` mean? ie, what does the postfix `.` signify?

So it looks like an understanding of [predicate types/logic](https://en.wikipedia.org/wiki/First-order_logic) is assumed?

`Universal quantification` is normally written as `∀`, which you can read as "for all", and means roughly what it sounds like: in a logical statement resembling "∀x. ..." whatever is in place of the "..." is true for all possible "x" you could choose from whatever set of things is being quantified over.

http://stackoverflow.com/questions/14299638/existential-vs-universally-quantified-types-in-haskell

So, a universally quantified type like `forall a. a -> a` means that, for any possible type "a", we can implement a function whose type is `a -> a`. And indeed we can:

**Comment by paf31** [comment]
I would say it's explained in section [3.4](https://leanpub.com/purescript/read#leanpub-auto-quantified-types). I don't want to go into such detail as explaining the dot, since it's just syntax.
