### ISSUE TITLE
insertEntry example is wrong

### ISSUE THREAD

**Issue by kristianmandrup** [paf31/purescript-book#56]
Let’s also test showEntry by creating an address book entry record containing our example address:

`> let entry = { firstName: "John", lastName: "Smith", address: address }`

A little later.. but `example` has never been defined

`> :type insertEntry example`

AddressBook -> AddressBook

So instead we get an error. Then I try using `entry` (the "example" entry defined earlier)

```
> :type insertEntry entry
List                                
  { firstName :: String             
  , lastName :: String              
  , address :: { street :: String   
               , city :: String     
               , state :: String    
               }                    
  }                                 
-> List                             
     { firstName :: String          
     , lastName :: String           
     , address :: { street :: String
                  , city :: String  
                  , state :: String 
                  }                 
     }                              
```

Why do I get `List` and not `AddressBook` !?

**Comment by paf31** [comment]
This will be fixed in the upcoming release. See the 0.10 branch.
