### ISSUE TITLE
Typo in: 6.9 Functional Dependencies

### ISSUE THREAD

**Issue by LiamGoodacre** [paf31/purescript-book#60]
The example fundep is `stream -> element` but in the next paragraph it refers to it by `list -> element`.

> ``` purescript
> class Stream stream element | stream -> element where
>   uncons :: stream -> Maybe { head :: element, tail :: stream }
> ```
> Here, `list -> element` is called a functional dependency.

**Comment by paf31** [comment]
Oops, thanks!

**Comment by paf31** [comment]
Making a patch release for this now, thanks!
