### ISSUE TITLE
Strange code formatting in 6.11's exercises

### ISSUE THREAD

**Issue by LiamGoodacre** [paf31/purescript-book#61]
It should probably look like this:
``` purescript
class Monoid m <= Action m a where
  act :: m -> a -> a
```

However it comes out like this:
``` purescript
class  Monoid   m   <=   Action   m   a   where
    act   ::   m   ->   a   ->   a
```

Similarly with the other two examples.

Browser: Firefox 50.0, macOS Sierra

**Comment by Cmdv** [comment]
Potential solutions to the issue: 
1. there seems to be some hidden characters / blank spaces in the markdown (view line 576, 578 in image) 

2. Code sample only seem to fail when with indented sections that use `X>`
I can't seem to find `X>` in the [Markua specs](https://leanpub.com/markua/read) which is what LeanPub uses.

![screen shot 2016-12-02 at 14 11 12](https://cloud.githubusercontent.com/assets/3036557/20836868/3b264704-b899-11e6-9f78-4ed55d68c58d.png)

**Comment by paf31** [comment]
Looks like a CSS bug. If I remove the padding and margin from things with the `pre code` selector, it looks fine. 

cc @leanpub Not sure how to file a bug report ...

**Comment by paf31** [comment]
I've filed a bug report on the LeanPub google group, so I'll close this.
