### ISSUE TITLE
Chapter 5 b - suggestions 

### ISSUE THREAD

**Issue by Cmdv** [paf31/purescript-book#62]
## 5.17 - **[Computing Bounding Rectangles](https://github.com/paf31/purescript-book/blob/master/text/chapter5.md#computing-bounding-rectangles)**

> and uses an infix operator alias `\/` to compute the union of the two bounding rectangles.

I ended up trying to find that `\/` infix operator on pursuit [here](https://pursuit.purescript.org/packages/purescript-coroutines/3.1.0/docs/Control.Coroutine#v:(\/)) but I don't think this is the right operator for it's use here.

**Comment by paf31** [comment]
I'll move this into a comment on the other thread, thanks!

**Comment by Cmdv** [comment]
@paf31 it's cool I'll do it if you want wasn't sure what would be easier for you, I'll just keep adding them to that issue
