### ISSUE TITLE
3.2 - Some dependencies are missing

### ISSUE THREAD

**Issue by bouzuya** [paf31/purescript-book#63]
3.2 Project Setup https://leanpub.com/purescript/read#leanpub-auto-project-setup

- `import Control.Plus (empty)` requires `purescript-control`.
- `import Data.Maybe (Maybe)` should depends directly on `purescript-maybe`.

`exercises/chapter3/bower.json`

```
   ],
   "dependencies": {
     "purescript-lists": "^3.0.0",
-    "purescript-console": "^2.0.0"
+    "purescript-console": "^2.0.0",
+    "purescript-control": "^2.0.0",
+    "purescript-maybe": "^2.0.1"
   },
   "devDependencies": {
     "purescript-psci-support": "^2.0.0"
```

**Comment by paf31** [comment]
These should be pulled in as transitive dependencies when you run `bower update`.
