### ISSUE TITLE
Chapter 3 Math.pi exercise – Unkown value Math.pi

### ISSUE THREAD

**Issue by naomik** [paf31/purescript-book#68]
**Chapter 3, exercise 1**

> *“(Easy) Use the Math.pi constant to write a function circleArea which computes the area of a circle with a given radius. Test your function using PSCi (Hint: don’t forget to import pi by modifying the import Math statement).”*

In PSCi

```
> import Math
> Math.pi
Error found:
in module $PSCI
at  line 1, column 1 - line 1, column 6

  Unknown value Math.pi
```

@soupi helped me out in the IRC channel explaining that I should change my import to either

```
> import Math as Math
> Math.pi
3.141592653589793
```

or

```
> import Math (pi)
> pi
3.141592653589793
```

I thought this information might be helpful to people attempting the exercises before the subtleties of `import` are explained

**Comment by paf31** [comment]
I'll add a note in the book, thanks!
