### ISSUE TITLE
Chapter 8, `(b : bs)`?

### ISSUE THREAD

**Issue by craigdallimore** [paf31/purescript-book#69]
Hello!

In the [folding with monads](https://github.com/paf31/purescript-book/blob/master/text/chapter8.md#folding-with-monads) section, there is this example code.

```
foldM f a (b : bs) = do
  a' <- f a b
  foldM f a' bs
```

As far as I understand, the `(b : bs)` syntax is no longer correct PureScript?

**Comment by paf31** [comment]
Yes, it's valid again, but it means something different. Previously it was used to destructure arrays, but now it's an alias for the `Cons` constructor on lists. The alias is defined in `Data.List`.
