### ISSUE TITLE
Chapter 8 - Text 8.16 - return is not longer used in PureScript

### ISSUE THREAD

**Issue by NicholasAaronBrady** [paf31/purescript-book#71]
I spent a while trying to figure out what/where `return` comes from before I found that it is something that no longer exists in PureScript here: https://github.com/purescript/purescript/wiki/Differences-from-Haskell#return
```
main = do
    config <- catchException printException readConfig
    runApplication config
  where
    printException e = do
      log (message e)
      return defaultConfig”
```

**Comment by paf31** [comment]
This will be fixed in the upcoming release. Thanks for the report!
