### ISSUE TITLE
Order chapters lexicographically

### ISSUE THREAD

**Issue by alex-deas** [paf31/purescript-book#72]
Niggling annoyance of mine, but when viewing the chapters though most tools they will be ordered lexicographically, resulting in:

![screenshot from 2017-03-31 22 59 01](https://cloud.githubusercontent.com/assets/12813479/24570952/4ae6965a-1666-11e7-8978-730217e30a59.png)

This could be fixed by adding `01`, `02`... for chapters below 10.

**Comment by paf31** [comment]
This is the filename format used by LeanPub, sorry. I couldn't find anything in their docs about allowing this, and the md files aren't really meant for reading directly anyway, so I'd prefer to leave it as it is.
