### ISSUE TITLE
Chapter 6 - Maybe Monoid instances removed from `purescript-monoids`.

### ISSUE THREAD

**Issue by taylor1791** [paf31/purescript-book#74]
Section 6.6 says the following. 

> This approach is taken in PureScript’s standard libraries, for example in purescript-monoids, where the Maybe a type has multiple valid instances for the Monoid type class.

It appears that those two instances were removed in https://github.com/purescript/purescript-monoid/commit/8a746a769abc66829e9c507b5d1b0478bd368781#diff-8907734265fd7027c4a7979902f3eceaL30 and added to `data-maybe`.

Also, I believe that `purescript-monoids` is actually `purescript-monoid`.

**Comment by paf31** [comment]
This will be fixed in the upcoming release, thanks!
