### ISSUE TITLE
Chapter 6 - Invalid reference to "parentheses" in Typeclass definition in section 6.5

### ISSUE THREAD

**Issue by jasontbradshaw** [paf31/purescript-book#79]
The beginning of section 6.5 as it currently stands reads (emphasis mine):

> ```purescript
> threeAreEqual :: forall a. Eq a => a -> a -> a -> Boolean
> threeAreEqual a1 a2 a3 = a1 == a2 && a2 == a3
> ```
> 
> The type declaration looks like an ordinary polymorphic type defined using forall. However, **there is a type class constraint in parentheses**, separated from the rest of the type by a double arrow =>.

It seems that either there should be parentheses in the code example, or the text should be changed.

I don't actually know PureScript, so I'm not sure which is the correct solution.

**Comment by mpriestman** [comment]
Perhaps the first line should read: `threeAreEqual :: forall a. (Eq a) => a -> a -> a -> Boolean`

**Comment by paf31** [comment]
This will be fixed in the upcoming release, thanks!
