### ISSUE TITLE
Chapter 7 - Typo in code example in section 7.9

### ISSUE THREAD

**Issue by jasontbradshaw** [paf31/purescript-book#80]
The following code example has a typo:

> Test this value in PSCi (this result has been formatted):
> 
> ```
> > import Data.AddressBook
> 
> > examplePerson
> Person
>   { firstName: "John",
>   , lastName: "Smith",
>   , address: Address
>       { street: "123 Fake St."
>       , city: "FakeTown"
>       , state: "CA"
>       },
>   , phones: [ PhoneNumber
>                 { type: HomePhone
>                 , number: "555-555-5555"
>                 }
>             , PhoneNumber
>                 { type: CellPghone
>                 , number: "555-555-0000"
>                 }
>             ]
>   }  
> ```

"CellPghone" should be "CellPhone".

**Comment by paf31** [comment]
Fixed in the upcoming release, thanks!
