### ISSUE TITLE
Chapter 3 Compilation ErrorParsingModule Errors 

### ISSUE THREAD

**Issue by joshreuben456** [paf31/purescript-book#85]
I'm on **Pulp version 11.0.0 purs version 0.11.4**
master branch had 21 compilation errors - based on https://github.com/paf31/purescript-book/issues/78 I tried switching to branch **0.11.3** which uses *"purescript-lists": "^4.0.0"* - still get 4 compilation errors:

### Error 1 of 4:
  at bower_components/purescript-arrays/src/Data/**Array.purs** line 168, column 1 - line 168, column 1

Unable to parse module:
**unexpected comma in constraints.**

Class constraints in type annotations can no longer be grouped in parentheses.
Each constraint should now be separated by `=>`, for example:
    `(Applicative f, Semigroup a) => a -> f a -> f a`
  would now be written as:
    `Applicative f => Semigroup a => a -> f a -> f a`.

    expecting indentation past column 1, (, qualifier, proper name, operator or ->

### Error 2 of 4:

  at bower_components/purescript-arrays/src/Data/Array/**ST.purs** line 34, column 34 - line 34, column 34

Unable to parse module:
**The `*` symbol is no longer used for the kind of types.**
  The new equivalent is the named kind `Type`.

### Error 3 of 4:

  at bower_components/purescript-proxy/src/Type/**Proxy.purs** line 55, column 21 - line 55, column 21

Unable to parse module:
**The `*` symbol is no longer used for the kind of types.**
The new equivalent is the named kind `Type`.

### Error 4 of 4:

  at bower_components/purescript-strings/src/Data/String/**Regex.purs** line 29, column 1 - line 29, column 1

Unable to parse module:
**The `*` symbol is no longer used for the kind of types.**
  The new equivalent is the named kind `Type`.

**Comment by paf31** [comment]
If you are using the 0.11.x series, then the book has not been updated yet, but you can find updated code on the 0.11 branch here. Thanks.
