### ISSUE TITLE
Chapter 2 - PSCi "let" statement no longer works

### ISSUE THREAD

**Issue by dominicprior** [paf31/purescript-book#87]
In chapter 2, `let double x = x * 2` should be `double x = x * 2`.

**Comment by dominicprior** [comment]
Really nice book though.  A genuine Work of Art!

**Comment by paf31** [comment]
Thanks! The book hasn't been updated for 0.11.x yet. I'm a bit behind but it's on my todo list.

**Comment by paf31** [comment]
This will be fixed in the upcoming release, thanks!
