### ISSUE TITLE
non-total function in ch1

### ISSUE THREAD

**Issue by JulianLeviston** [paf31/purescript-book#89]
There is a piece of text in chapter one that read:

> A more involved example shows that type-correctness can be confirmed without type annotations, even when there exist types which are unknown to the compiler:

which is then followed by a non-total function:

```
iterate f 0 x = x
iterate f n x = iterate f (n - 1) (f x)
```

I think this function should be made to be total, or a different total function should be used in its stead if that's not very elegant:

```
iterate f n x = 
    if n > 0 then iterate f (n - 1) (f x) else x
```

```
iterate f n x =
    case n > 0 of
        True -> iterate f (n - 1) (f x)
        False -> x
```

etc.

**Comment by paf31** [comment]
why do you say it's not total?

**Comment by JulianLeviston** [comment]
because `iterate (+1) (-1) 5` ?

**Comment by JulianLeviston** [comment]
Maybe it's not important, I don't know. It just stuck out for me.

**Comment by paf31** [comment]
I'm going to leave this as it is actually, but thank you anyway. I need an example which is short and understandable, so I don't want to use guards to test for `n <= 0` at this early point in the book, for example. And the text does say "type correctness", which is true here.

**Comment by JulianLeviston** [comment]
Fair enough. It *is* your book :) 👍
