### ISSUE TITLE
Chapter 3 - Missing word "be"

### ISSUE THREAD

**Issue by JulianLeviston** [paf31/purescript-book#90]
The sentence

> Now let's define a third type synonym, for our address book data structure, which will represented simply as a linked list of entries:

should read

> Now let's define a third type synonym, for our address book data structure, which will be represented simply as a linked list of entries:

 https://github.com/paf31/purescript-book/blame/master/text/chapter3.md#L257

**Comment by paf31** [comment]
This will be fixed in the upcoming release, thanks for the report!
